# Generated by Django 3.1.7 on 2021-03-03 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20210303_1227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author_name',
            new_name='author',
        ),
    ]
