# Generated by Django 3.1.7 on 2021-03-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20210303_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='counter_view',
        ),
    ]
